name: Flutter CI
on:
  pull_request:
  push:
    branches:
      - master
      - feature/add-ci

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Android NDK toolchain Setup
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
          cache-key: flutter-mac
          architecture: x64
      - name: Install Flutter
        run: |
          flutter config --enable-web --enable-ios --enable-android
          flutter pub get
      - name: Check format
        run: flutter format --set-exit-if-changed . || { echo -e "${RED}Invalid format" ; exit 1; }
      - name: Run Linter
        run: flutter analyze . || { echo -e "${RED}Linter error" ; exit 1; }
      - name: Build Web
        run: cd example && flutter build web
      - name: Build Android
        run: cd example && flutter build apk --debug
      - name: Build Ios
        run: cd example && flutter build ipa
